import "./styles/globals.scss";
import { Layout } from "./components";

export const metadata = {
  title: "GraphQl Blog CMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
